### ISSUE TITLE
Clang warns char comparison with negative integers is always false

### ISSUE THREAD

**Issue by scothalverson** [lanl/Draco#688]
See below for an example where this warning appears.  This results in hundreds of warning messages when compiling with Clang.

https://github.com/lanl/Draco/blob/bc8d5bf4a660a8f0b930e0185fe940477df8101a/src/ds%2B%2B/terminal/terminal.h#L384

an example error message:
`Draco/src/ds++/terminal/terminal.h:380:19: warning: result of comparison of constant -61 with expression of type 'char' is always false [-Wtautological-constant-out-of-range-compare]`

**Comment by KineticTheory** [comment]
This was fixed in #687.

**Comment by scothalverson** [comment]
I don't think that suppresses the warnings under Clang.  I'm on branch `develop` checked out ~1h ago and I'm still seeing it.

**Comment by KineticTheory** [comment]
> I don't think that suppresses the warnings under Clang. I'm on branch `develop` checked out ~1h ago and I'm still seeing it.

We only support clang-6.0 and the provided suppression works for this version of clang.  BTW, this code is copied from https://github.com/certik/terminal.  Maybe @certik can take a look at this issue.  If not, I'll come back to it once we adopt a newer LLVM toolchain.

**Comment by certik** [comment]
@scothalverson thanks for reporting it. Let me have a look.

**Comment by scothalverson** [comment]
Ok.  I'm using Clang/LLVM 10.0.0.  Not sure if this matters to you guys, but Clang as a CUDA compiler is broken prior to clang 10.0.0 develop for CUDA >= 10.x.

**Comment by KineticTheory** [comment]
@scothalverson We haven't looked at clang's GPU offload capability.  Out of curiosity, what do you do for F90 when you use clang-10?

**Comment by certik** [comment]
@scothalverson I can't see Clang 10.0.0 in the downloads: http://releases.llvm.org/. Are you using 9.0.0, or the latest git version?

**Comment by certik** [comment]
I am installing the latest development version of Clang using Spack: `spack install -j4 llvm@develop`. I've been compiling using `clang++ -g -I. test_terminal.cpp -o test_terminal -Wall -Wextra --std=c++11
` and that does not seem to show any warnings using Clang 6.0.0 in Ubuntu 18.04.

**Comment by certik** [comment]
Weird, even with the latest Clang 10.0.0 (trunk), and explicitly adding the option:
```
clang++ -g -I. test_terminal.cpp -o test_terminal -Wall -Wextra -Wtautological-constant-out-of-range-compare --std=c++11
```
I can't see any warnings.
```
$ clang++ --version
clang version 10.0.0 (trunk)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ondrej/repos/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.3.0/llvm-develop-4yxl5v6yhu62prnxmhzaaqfopje5rpmp/bin
```
@scothalverson how did you get the warnings? I will fix it once I can reproduce it on my machine.

**Comment by scothalverson** [comment]
It might be worth noting that I'm forcing c++17 everywhere.  Not sure that would cause this difference though.

@KineticTheory,  I'm specifiying gfortran as my F90 compiler.

**Comment by certik** [comment]
I tried C++17:
```
$ clang++ -g -I.  -Wall -Wextra -Wtautological-constant-out-of-range-compare --std=c++17 test_terminal.cpp -o test_terminal
```
and still there are no warnings. I even tried `--std=c++2a`. I'll stop by your office. I would like to figure this out and fix it.

**Comment by certik** [comment]
I figured out how to reproduce this. I have to pass in the `-funsigned-char` compiler flag to force `char` to be `unsigned char`, then I get all the warnings. Those were fixed in https://github.com/certik/terminal/pull/37. I am now going to update Draco.

**Comment by certik** [comment]
@scothalverson give the PR #691 a shot, I think it fixes it.
